services:
  service1:
    build: ./service_1
    container_name: service1
    # no ports here
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  service2:
    build: ./service_2
    container_name: service2
    # no ports here
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
